### ISSUE TITLE
There isn't a clear way to create a json graph (eg from a gm graph)

### ISSUE THREAD

**Issue by drussel** [gyuho/goraph#1]
The function JSONGraph loads from a JSON graph, but how do I write it (eg to use the conversion to dot).

**Comment by gyuho** [comment]
Did a lot of refactoring with `interface`. https://github.com/gyuho/goraph/pull/49.
This is the finalized version of `graph` package. You can write your own JSON parser
using `io.Reader`. e.g. https://github.com/gyuho/goraph/blob/master/graph/default_graph.go#L278-L305
