### ISSUE TITLE
duplicate return value

### ISSUE THREAD

**Issue by ggaaooppeenngg** [gyuho/goraph#10]
https://github.com/gyuho/goraph/blob/refactor/graph/graph.go#L74

this line nil error can denote true,I think a bool return value is a duplicate.

**Comment by gyuho** [comment]
I agree. I will update as you suggest. Thanks!

**Comment by gyuho** [comment]
Thanks, https://github.com/gyuho/goraph/commit/d84484f1ebe3f23e3e0de05c70ba3653561519ce

**Comment by gyuho** [comment]
Just finished a huge refactoring, if you are still interested.
https://github.com/gyuho/goraph/pull/49
