### ISSUE TITLE
append delete or copy delete

### ISSUE THREAD

**Issue by ggaaooppeenngg** [gyuho/goraph#11]
https://github.com/gyuho/goraph/blob/refactor/graph/graph.go#L280

why not just,`d.outEdge[src] = append(d.OutEdges[src][:idx],d.OutEdges[src][idx+1:]...)`?
Is there any reason for efficiency?

**Comment by gyuho** [comment]
I changed a lot of code base, with much simplification. Much can be simply done with map data structure.

**Comment by gyuho** [comment]
Just finished a huge refactoring, if you are still interested.
https://github.com/gyuho/goraph/pull/49
