### ISSUE TITLE
Do you need HeiankyoView?

### ISSUE THREAD

**Issue by akiradeveloper** [gyuho/goraph#2]
Hi, I started Go and I was searching for a graph library in Go, and found this project. Looks good to me.

I think you plan to implement a module to import/export from/to dot language from and it's really a good idea. But, how about other visualization technique such as treemap?

HeiankyoView, I have implemented, is another method of visualizing tree structure and now implemented in Python. https://github.com/akiradeveloper/HeiankyoView
I have a plan to rewrite this in Go and probably the best way is to construct it on top of standard graph library, which I suppose this is.

If I implement HeiankyoView on top of goraph. Will you merge? (drill down viz/heiankyoview)

or do you introduce me better graph library?

**Comment by gyuho** [comment]
Just finished a huge refactoring, if you are still interested.
https://github.com/gyuho/goraph/pull/49
