### ISSUE TITLE
NanoMSG / Goraph

### ISSUE THREAD

**Issue by lucmichalski** [gyuho/goraph#59]
Hi,

Just had a quick thought about how we could implement these patterns to nanomsg (https://github.com/gdamore/mangos) in order to dynamic distributed searches like (https://daniel-j-h.github.io/post/distributed-search-nanomsg-bond/). I am working on an advanced version of Iris ( http://iris.karalabe.com/) with an Etcd store in order to dynamically dispatch queries.

That would be awesome.

Hope u can match my idea.

Cheers,
Luc Michalski

**Comment by gyuho** [comment]
I am not sure how `goraph` would integrate into `nanomsg`.

I think graph algorithms vary a lot depending on its use cases, so you will
have to implement your own for best performance. But I will be glad to help
you, and if you need, you can just copy my library :)

And I am working on etcd too. So if you ever need any help, please ping us too.

Thanks,

**Comment by lucmichalski** [comment]
I wanted to use vulcand+etcd as a reverse proxy and then use maybe something like Iris or mangos to make distributed queries to several micro-services based on some regex rules based on routes or some variables passed between middlewares. My initial thought was based to query dynamicallly several social media apis (eg, https://github.com/manishrjain/gocrud/blob/master/example.md) and deal with some extend graphs
